#!/usr/bin/env python
from magicbandreader.led import LedController, LedColor


print('Constructing the LedControler instance, the lights should flash twice, slowly, in white:')
input("Press Enter to continue...")
led = LedController(.5, 40, 15)
print('Default blink() - lights should flask three times in blue:')
input("Press Enter to continue...")
led.blink(LedColor.BLUE)
print('Default lights_on() - lights will come on in red and stay lit:')
input("Press Enter to continue...")
led.lights_on(LedColor.RED)
print('Default lights_off() - lights will turn off and stay off:')
input("Press Enter to continue...")
led.lights_off()
print('Default fade_on() - lights will be green and slowly increase in brightness:')
input("Press Enter to continue...")
led.fade_on(LedColor.GREEN)
print('Default fade_off() - lights will slowly decrease in brightness:')
input("Press Enter to continue...")
led.fade_off()
print('Default color_chase() - an orange 8 pixel group will circle clockwise around the outer_pixels:')
input("Press Enter to continue...")
led.color_chase(LedColor.ORANGE)
print('Reverse color_chase() - a purple 8 pixel group will circle counter-clockwise around the outer_pixels:')
input("Press Enter to continue...")
led.color_chase(LedColor.PURPLE, reverse=True)
print('Larger Effect color_chase() - an orange 15 pixel group will circle clockwise around the outer_pixels:')
input("Press Enter to continue...")
led.color_chase(LedColor.ORANGE, effect_width=15)
print('Larger Effect Reverse color_chase() - a purple 15 pixel group will circle counter-clockwise around the outer_pixels:')
input("Press Enter to continue...")
led.color_chase(LedColor.PURPLE, reverse=True, effect_width=15)
print('Default spin() - Executes 4 colors chases in pink with decreasing sleep time (last two are the same speed)')
input("Press Enter to continue...")
led.spin(LedColor.PINK)
print('Done!')
